author:
  name: s-Ruthless
  version: 1.0

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&useSSL=false&characterEncoding=UTF-8
#    username: blog
#    password: root
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/view/

logging:
  config: classpath:log4j2.xml

mybatis-plus:
  global-config:
    banner: false

send:
  url: http://127.0.0.1:5700